/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, AiModel as PrismaAiModel } from "@prisma/client";

export class AiModelServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.AiModelCountArgs, "select">): Promise<number> {
    return this.prisma.aiModel.count(args);
  }

  async aiModels(args: Prisma.AiModelFindManyArgs): Promise<PrismaAiModel[]> {
    return this.prisma.aiModel.findMany(args);
  }
  async aiModel(
    args: Prisma.AiModelFindUniqueArgs
  ): Promise<PrismaAiModel | null> {
    return this.prisma.aiModel.findUnique(args);
  }
  async createAiModel(args: Prisma.AiModelCreateArgs): Promise<PrismaAiModel> {
    return this.prisma.aiModel.create(args);
  }
  async updateAiModel(args: Prisma.AiModelUpdateArgs): Promise<PrismaAiModel> {
    return this.prisma.aiModel.update(args);
  }
  async deleteAiModel(args: Prisma.AiModelDeleteArgs): Promise<PrismaAiModel> {
    return this.prisma.aiModel.delete(args);
  }
}
